* Introduction

This document presents guidelines for translations of sentences in Standard Mandarin which are primarily aimed to language learners of that language.

* 1. Prioritize full conveyance of meanings over naturality of speech

There are some commonly used words in Chinese which convey greater meanings than their counterparts in other languages (especially terms for family members). For example, 外婆 means "maternal grandmother" and 奶奶 "paternal grandmothe". When someone greet their grandmother in Chinese, they either say 外婆 or 奶奶. Contrarily, it is not common to hear English native speakers say "paternal grandmother" or "maternal grandmother" when greeting.



There's a trade-off when showing full meaning of words: sentences don't sound too natural. When the subtitles are intended to be read by Chinese learners, the learner when reading the subtitles in their native language, he/she might be more interested in reading a translation that convey the same meaning instead of reading a translation that sounds natural. Therefore, subtitles should give higher priority to expressing the same meaning as the original sentence rather than trying to sound natural.

** Example

The following =en= translation doesn't comply with this rule.

#+BEGIN_SRC sh
- id: 93b6590f-6567-4fbe-a667-8f35b67a5024
  zh-hans: 外婆，您好！
  en: Grandmother, hello!
#+END_SRC

It should be written like this:

#+BEGIN_SRC sh
- id: 93b6590f-6567-4fbe-a667-8f35b67a5024
  zh-hans: 外婆，您好！
  en: Maternal grandmother, hello!
#+END_SRC

The second translation doesn't sound natural, but we are prioritizing full conveyance of meaning over naturality of speech.

* 2. Vertical proximity of translations

There should be a balance between naturality of speech and the vertical proximity of words in the original language.

Sometimes when trying to follow this rule, it might be difficult to ensure naturality of speech. In such cases, prioritize naturality of speech.

** Example

The following =en= translation doesn't comply with this rule.

#+begin_src yaml
- id: 74fc4823-1700-4e68-b878-ff8638db231d
  zh-hans: 养花是不太难。
  en: It is not too difficult to raise flowers.
#+end_src

It should be written as shown below:

#+begin_src yaml
- id: 74fc4823-1700-4e68-b878-ff8638db231d
  zh-hans: 养花是不太难。
  en: Raising flowers is not too difficult.
#+end_src

** Example

The following =en= translation doesn't comply with this rule.

#+begin_src yaml
- id: 19dd003c-9982-4f04-a0d5-ea6a6696f223
  zh-hans: 你们都很喜欢，我太高兴了。
  en: I am very happy that you all enjoyed it.
#+end_src

It should be written as shown below:

#+begin_src yaml
- id: 19dd003c-9982-4f04-a0d5-ea6a6696f223
  zh-hans: 你们都很喜欢，我太高兴了。
  en: You all enjoyed it, I am very happy.
#+end_src

** Example

The following =en= translation doesn't comply with this rule because "teahouse" appears at the beginning of the sentence while "茶馆" appears at the end of the sentence.

#+begin_src yaml
- id: c0198d9f-60ef-4b8a-b9a3-f6a16ef4dbaf
  zh-hans: 这就是我常说的老茶馆。
  en: This is the old teahouse I often talk about.
#+end_src

Someone could think that a translation that comply with this rule is "This is I often talk about of the old teahouse", but it is not grammatically correct.

* 3. Show direct translations as much as possible

Since subtitles are aimed for language learners, it sounds reasonable to try to show as much as possible direct translations of words so as to give learners the opportunity to know the specific meaning of words.

** Example

The following =en= translation doesn't comply with this rule.

#+begin_src yaml
- id: 283dd850-6858-4acb-92f0-0bf73b2501ab
  zh-hans: 女儿看大家都不同意，
  en: My daughter sees that no one agreed.
#+end_src

It should be written as shown below:

#+BEGIN_SRC yaml
- id: 283dd850-6858-4acb-92f0-0bf73b2501ab
  zh-hans: 女儿看大家都不同意，
  en: My daughter sees that everyone did not agree,
#+END_SRC

The first and the second English translation convey the same meaning. However, the first translation =大家= does not include the direct translation (i.e. "everyone"), while the second translation does include it.
